import { Country, Currency } from './types';

// Approximate exchange rates relative to USD (1 USD = X Currency)
// Ordered loosely by global trade usage
export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'United States Dollar', rateToUSD: 1, symbol: '$' },
  { code: 'EUR', name: 'Euro', rateToUSD: 0.92, symbol: '€' },
  { code: 'JPY', name: 'Japanese Yen', rateToUSD: 150.2, symbol: '¥' },
  { code: 'GBP', name: 'British Pound', rateToUSD: 0.79, symbol: '£' },
  { code: 'CNY', name: 'Chinese Yuan', rateToUSD: 7.19, symbol: '¥' },
  { code: 'AUD', name: 'Australian Dollar', rateToUSD: 1.53, symbol: 'A$' },
  { code: 'CAD', name: 'Canadian Dollar', rateToUSD: 1.35, symbol: 'C$' },
  { code: 'CHF', name: 'Swiss Franc', rateToUSD: 0.88, symbol: 'Fr' },
  { code: 'HKD', name: 'Hong Kong Dollar', rateToUSD: 7.82, symbol: 'HK$' },
  { code: 'SGD', name: 'Singapore Dollar', rateToUSD: 1.34, symbol: 'S$' },
  { code: 'INR', name: 'Indian Rupee', rateToUSD: 83.0, symbol: '₹' },
  { code: 'KRW', name: 'South Korean Won', rateToUSD: 1330.0, symbol: '₩' },
  { code: 'MXN', name: 'Mexican Peso', rateToUSD: 17.1, symbol: '$' },
  { code: 'BRL', name: 'Brazilian Real', rateToUSD: 4.95, symbol: 'R$' },
  { code: 'IDR', name: 'Indonesian Rupiah', rateToUSD: 15600.0, symbol: 'Rp' },
  { code: 'VND', name: 'Vietnamese Dong', rateToUSD: 24600.0, symbol: '₫' },
  { code: 'RUB', name: 'Russian Ruble', rateToUSD: 92.5, symbol: '₽' },
  { code: 'TRY', name: 'Turkish Lira', rateToUSD: 30.5, symbol: '₺' },
  { code: 'SAR', name: 'Saudi Riyal', rateToUSD: 3.75, symbol: '﷼' },
  { code: 'THB', name: 'Thai Baht', rateToUSD: 35.8, symbol: '฿' },
  { code: 'MYR', name: 'Malaysian Ringgit', rateToUSD: 4.77, symbol: 'RM' },
  { code: 'COP', name: 'Colombian Peso', rateToUSD: 3920.0, symbol: '$' },
  { code: 'PHP', name: 'Philippine Peso', rateToUSD: 56.0, symbol: '₱' },
  { code: 'ZAR', name: 'South African Rand', rateToUSD: 19.0, symbol: 'R' },
  { code: 'EGP', name: 'Egyptian Pound', rateToUSD: 30.9, symbol: '£' },
  { code: 'PKR', name: 'Pakistani Rupee', rateToUSD: 279.0, symbol: '₨' },
  { code: 'IQD', name: 'Iraqi Dinar', rateToUSD: 1310.0, symbol: 'ع.د' },
  { code: 'IRR', name: 'Iranian Rial', rateToUSD: 42000.0, symbol: '﷼' }, // Official rate, market is higher
  { code: 'CLP', name: 'Chilean Peso', rateToUSD: 965.0, symbol: '$' },
  { code: 'NGN', name: 'Nigerian Naira', rateToUSD: 1500.0, symbol: '₦' },
  { code: 'KES', name: 'Kenyan Shilling', rateToUSD: 145.0, symbol: 'KSh' },
  { code: 'LAK', name: 'Lao Kip', rateToUSD: 20800.0, symbol: '₭' },
  { code: 'KHR', name: 'Cambodian Riel', rateToUSD: 4100.0, symbol: '៛' },
  { code: 'UZS', name: 'Uzbekistani Som', rateToUSD: 12400.0, symbol: 'soʻm' },
  { code: 'TZS', name: 'Tanzanian Shilling', rateToUSD: 2540.0, symbol: 'TSh' },
  { code: 'UGX', name: 'Ugandan Shilling', rateToUSD: 3850.0, symbol: 'USh' },
  { code: 'LBP', name: 'Lebanese Pound', rateToUSD: 15000.0, symbol: 'ل.ل' },
  { code: 'ARS', name: 'Argentine Peso', rateToUSD: 830.0, symbol: '$' },
  { code: 'HUF', name: 'Hungarian Forint', rateToUSD: 360.0, symbol: 'Ft' },
  { code: 'PLN', name: 'Polish Złoty', rateToUSD: 4.0, symbol: 'zł' },
];

export const COUNTRIES: Country[] = [
  { name: 'United States', currencyCode: 'USD', flagEmoji: '🇺🇸' },
  { name: 'Eurozone (EU)', currencyCode: 'EUR', flagEmoji: '🇪🇺' },
  { name: 'Japan', currencyCode: 'JPY', flagEmoji: '🇯🇵' },
  { name: 'United Kingdom', currencyCode: 'GBP', flagEmoji: '🇬🇧' },
  { name: 'China', currencyCode: 'CNY', flagEmoji: '🇨🇳' },
  { name: 'Australia', currencyCode: 'AUD', flagEmoji: '🇦🇺' },
  { name: 'Canada', currencyCode: 'CAD', flagEmoji: '🇨🇦' },
  { name: 'Switzerland', currencyCode: 'CHF', flagEmoji: '🇨🇭' },
  { name: 'Hong Kong', currencyCode: 'HKD', flagEmoji: '🇭🇰' },
  { name: 'Singapore', currencyCode: 'SGD', flagEmoji: '🇸🇬' },
  { name: 'India', currencyCode: 'INR', flagEmoji: '🇮🇳' },
  { name: 'South Korea', currencyCode: 'KRW', flagEmoji: '🇰🇷' },
  { name: 'Mexico', currencyCode: 'MXN', flagEmoji: '🇲🇽' },
  { name: 'Brazil', currencyCode: 'BRL', flagEmoji: '🇧🇷' },
  { name: 'Indonesia', currencyCode: 'IDR', flagEmoji: '🇮🇩' },
  { name: 'Vietnam', currencyCode: 'VND', flagEmoji: '🇻🇳' },
  { name: 'Russia', currencyCode: 'RUB', flagEmoji: '🇷🇺' },
  { name: 'Turkey', currencyCode: 'TRY', flagEmoji: '🇹🇷' },
  { name: 'Saudi Arabia', currencyCode: 'SAR', flagEmoji: '🇸🇦' },
  { name: 'Thailand', currencyCode: 'THB', flagEmoji: '🇹🇭' },
  { name: 'Malaysia', currencyCode: 'MYR', flagEmoji: '🇲🇾' },
  { name: 'Colombia', currencyCode: 'COP', flagEmoji: '🇨🇴' },
  { name: 'Philippines', currencyCode: 'PHP', flagEmoji: '🇵🇭' },
  { name: 'South Africa', currencyCode: 'ZAR', flagEmoji: '🇿🇦' },
  { name: 'Egypt', currencyCode: 'EGP', flagEmoji: '🇪🇬' },
  { name: 'Pakistan', currencyCode: 'PKR', flagEmoji: '🇵🇰' },
  { name: 'Iraq', currencyCode: 'IQD', flagEmoji: '🇮🇶' },
  { name: 'Iran', currencyCode: 'IRR', flagEmoji: '🇮🇷' },
  { name: 'Chile', currencyCode: 'CLP', flagEmoji: '🇨🇱' },
  { name: 'Nigeria', currencyCode: 'NGN', flagEmoji: '🇳🇬' },
  { name: 'Kenya', currencyCode: 'KES', flagEmoji: '🇰🇪' },
  { name: 'Laos', currencyCode: 'LAK', flagEmoji: '🇱🇦' },
  { name: 'Cambodia', currencyCode: 'KHR', flagEmoji: '🇰🇭' },
  { name: 'Uzbekistan', currencyCode: 'UZS', flagEmoji: '🇺🇿' },
  { name: 'Tanzania', currencyCode: 'TZS', flagEmoji: '🇹🇿' },
  { name: 'Uganda', currencyCode: 'UGX', flagEmoji: '🇺🇬' },
  { name: 'Lebanon', currencyCode: 'LBP', flagEmoji: '🇱🇧' },
  { name: 'Argentina', currencyCode: 'ARS', flagEmoji: '🇦🇷' },
  { name: 'Hungary', currencyCode: 'HUF', flagEmoji: '🇭🇺' },
  { name: 'Poland', currencyCode: 'PLN', flagEmoji: '🇵🇱' },
];
